Repository LeadingLog/reading-log, pull requests merged in 2025-05, with the labels that each got.

#56 타임라인 월 표시 UI 추가 및 년도 클릭 버튼 기능 추가
  .github/workflows/deploy.yml
  ReadingLogFrontend/src/components/common/YearSlideBar.tsx
  ReadingLogFrontend/src/components/homeLeft/TimeLine.tsx
  ReadingLogFrontend/src/components/homeRight/statsItems/StatsMonth.tsx
  ReadingLogFrontend/src/store/modalStore.ts
  ReadingLogFrontend/tailwind.config.js
Labels: ✨ Feature

#63 B aladin api
  .github/workflows/gradle.yml
  ReadingLogBackend/src/main/java/com/example/demo/aladinApi/AladinController.java
Labels: ✨ Feature

#67 관심도서 리스트 가져오기 (Mock 데이터 사용)
  ReadingLogFrontend/src/components/homeLeft/MyBookList.tsx
  ReadingLogFrontend/src/components/homeLeft/MyFavoriteList.tsx
  ReadingLogFrontend/src/components/homeTop/BookSearchResult.tsx
  ReadingLogFrontend/src/components/layout/LeftPage.tsx
  ReadingLogFrontend/src/mocks/dummyData/favoriteListData/favoriteListData.json
  ReadingLogFrontend/src/mocks/dummyData/favoriteListData/favoriteListData2.json
  ReadingLogFrontend/src/mocks/handlers/readingListHandlers.ts
  ReadingLogFrontend/src/types/tabName.ts
  ReadingLogFrontend/tailwind.config.js
Labels: ✨ Feature

#69 타임라인에 보여 질 년&월 도서 수 (Mock 데이터 사용)
  .github/workflows/deploy.yml
  ReadingLogFrontend/src/components/common/YearSlideBar.tsx
  ReadingLogFrontend/src/components/homeLeft/TimeLine.tsx
  ReadingLogFrontend/src/mocks/dummyData/timeLineReadingListData/ReadingList-2024.json
  ReadingLogFrontend/src/mocks/dummyData/timeLineReadingListData/ReadingList-2025.json
  ReadingLogFrontend/src/mocks/handlers/readingListHandlers.ts
  ReadingLogFrontend/src/store/useDateStore.ts
Labels: ✨ Feature

#72 이번 달 독서 리스트 가져오기 (Mock 데이터 사용)
  .github/workflows/deploy.yml
  ReadingLogFrontend/src/api/ThisMonthReadingListApi.ts
  ReadingLogFrontend/src/components/homeLeft/MyFavoriteList.tsx
  ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/BoxThisMonthReadingList.tsx
  ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/ItemReadStatus.tsx
  ReadingLogFrontend/src/components/modal/ModalTrackingPlan.tsx
  ReadingLogFrontend/src/mocks/dummyData/favoriteListData/favoriteListData2.json
  ReadingLogFrontend/src/mocks/dummyData/thisMonthReadingListData/thisMonthReadingList.json
  ReadingLogFrontend/src/mocks/dummyData/thisMonthReadingListData/thisMonthReadingList2.json
  ReadingLogFrontend/src/mocks/handlers/readingListHandlers.ts
  ReadingLogFrontend/src/types/monthReadingList.ts
Labels: ✨ Feature

#74 관심도서 API 요청 및 타입 파일 추가
  ReadingLogFrontend/src/api/myFavoriteListApi.ts
  ReadingLogFrontend/src/components/homeLeft/MyFavoriteList.tsx
  ReadingLogFrontend/src/mocks/handlers/readingListHandlers.ts
  ReadingLogFrontend/src/types/myFavoriteList.ts
Labels: 🔨 Refactor

#75 도서 필터별로 API 요청 구조 작성 및 각 요청 별로 리스트 표시 및 무한스크롤 구현
  ReadingLogFrontend/src/api/myReadingListApi.ts
  ReadingLogFrontend/src/components/common/BookImgList.tsx
  ReadingLogFrontend/src/components/homeLeft/MyBookList.tsx
  ReadingLogFrontend/src/components/homeRight/statsItems/StatsMonth.tsx
  ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/ItemReadStatus.tsx
  ReadingLogFrontend/src/mocks/dummyData/myReadingListData/myReadingList_all.json
  ReadingLogFrontend/src/mocks/dummyData/myReadingListData/myReadingList_all2.json
  ReadingLogFrontend/src/mocks/dummyData/myReadingListData/myReadingList_complete.json
  ReadingLogFrontend/src/mocks/dummyData/myReadingListData/myReadingList_complete2.json
  ReadingLogFrontend/src/mocks/dummyData/myReadingListData/myReadingList_noRead.json
  ReadingLogFrontend/src/mocks/dummyData/myReadingListData/myReadingList_noRead2.json
  ReadingLogFrontend/src/mocks/dummyData/myReadingListData/myReadingList_reading.json
  ReadingLogFrontend/src/mocks/dummyData/myReadingListData/myReadingList_reading2.json
  ReadingLogFrontend/src/mocks/handlers/readingListHandlers.ts
  ReadingLogFrontend/src/types/aladinApi.ts
  ReadingLogFrontend/src/types/monthReadingList.ts
  ReadingLogFrontend/src/types/myFavoriteList.ts
  ReadingLogFrontend/src/types/myReadingList.ts
  ReadingLogFrontend/src/types/readStatus.ts
Labels: ✨ Feature

#77 카카오 로그인 구현
  ReadingLogBackend/src/main/java/com/example/demo/user/Controller/UserController.java
  ReadingLogBackend/src/main/java/com/example/demo/user/Entity/KakaoProfile.java
  ReadingLogBackend/src/main/java/com/example/demo/user/Entity/KakaoTokenResponse.java
  ReadingLogBackend/src/main/java/com/example/demo/user/Entity/User.java
  ReadingLogBackend/src/main/java/com/example/demo/user/Service/ApiKeyService.java
  ReadingLogBackend/src/main/java/com/example/demo/user/Service/KakaoService.java
  ReadingLogBackend/src/main/java/com/example/demo/user/Service/UserService.java
Labels: ✨ Feature

#80 알라딘 API 키 추가
  ReadingLogBackend/docker-compose.yml
Labels: 🔨 Refactor

#87 내 독서 목록 필터 별 검색 독서 리스트 가져오기 (Mock 데이터 사용)
  ReadingLogFrontend/src/api/myReadingListSearchQueryApi.ts
  ReadingLogFrontend/src/components/common/BookImgList.tsx
  ReadingLogFrontend/src/components/homeLeft/MyBookList.tsx
  ReadingLogFrontend/src/mocks/handlers/readingListHandlers.ts
  ReadingLogFrontend/src/types/myReadingList.ts
  ReadingLogFrontend/tailwind.config.js
Labels: ✨ Feature

#91 Update AladinController.java edit
  ReadingLogBackend/src/main/java/com/example/demo/aladinApi/AladinController.java
Labels: ✨ Feature, 🔧 Fix

#89 알라딘 도서 검색 API 요청 코드 수정
  .github/workflows/deploy.yml
  ReadingLogFrontend/api/proxy.js
  ReadingLogFrontend/src/api/aladinApi.ts
  ReadingLogFrontend/src/components/homeTop/BookSearchResult.tsx
  ReadingLogFrontend/src/components/homeTop/MainBookSearch.tsx
  ReadingLogFrontend/src/mocks/handlers/bookHandlers.ts
Labels: 🔨 Refactor

#95 알라딘 요청 api 수정
  ReadingLogFrontend/src/api/aladinApi.ts
  ReadingLogFrontend/src/components/homeLeft/TimeLine.tsx
  ReadingLogFrontend/src/components/homeTop/BookSearchResult.tsx
  ReadingLogFrontend/src/components/homeTop/MainBookSearch.tsx
  ReadingLogFrontend/src/types/timeLine.ts
Labels: 🔨 Refactor

#97 이서연 : backdev 배포용
  ReadingLogBackend/src/main/java/com/example/demo/user/Entity/KakaoProfile.java
  ReadingLogBackend/src/main/java/com/example/demo/user/Repository/RefreshTokenRepository.java
Labels: ✨ Feature

#103 타임라인 월 표시 및 라인 관련 코드 정리
  ReadingLogFrontend/src/components/homeLeft/TimeLine.tsx
  ReadingLogFrontend/src/types/timeLine.ts
Labels: 🔨 Refactor

#116 연별 통계 페이지 수정
  .github/workflows/deploy.yml
  ReadingLogFrontend/src/api/ThisMonthReadingListApi.ts
  ReadingLogFrontend/src/api/aladinApi.ts
  ReadingLogFrontend/src/api/allReadingTimeApi.ts
  ReadingLogFrontend/src/api/myFavoriteListApi.ts
  ReadingLogFrontend/src/api/myReadingListApi.ts
  ReadingLogFrontend/src/api/myReadingListSearchQueryApi.ts
  ReadingLogFrontend/src/api/statsMonthApi.ts
  ReadingLogFrontend/src/api/statsYearApi.ts
  ReadingLogFrontend/src/api/timeLineReadingListApi.ts
  ReadingLogFrontend/src/api/todayReadingTimeApi.ts
  ReadingLogFrontend/src/components/common/TodayReadingTime.tsx
  ReadingLogFrontend/src/components/homeLeft/TimeLine.tsx
  ReadingLogFrontend/src/components/homeRight/statsItems/StatsYear.tsx
  ReadingLogFrontend/src/mocks/dummyData/statsYearListData/statsYearList.json
  ReadingLogFrontend/src/mocks/handlers/readingRecordHandlers.ts
  ReadingLogFrontend/src/types/statsYear.ts
  ReadingLogFrontend/tailwind.config.js
Labels: ✨ Feature
