Repository LeadingLog/reading-log, pull requests merged in 2025-06, with the labels that each got.

#124 알라딘 서버 API, 독서통계, 도서리스트 개발
  ReadingLogBackend/src/main/java/com/example/demo/aladinApi/AladinController.java
  ReadingLogBackend/src/main/java/com/example/demo/readingList/ReadingList.java
  ReadingLogBackend/src/main/java/com/example/demo/readingList/ReadingListController.java
  ReadingLogBackend/src/main/java/com/example/demo/readingList/ReadingListReaponseDto.java
  ReadingLogBackend/src/main/java/com/example/demo/readingList/ReadingListRepository.java
  ReadingLogBackend/src/main/java/com/example/demo/readingList/ReadingListService.java
  ReadingLogBackend/src/main/java/com/example/demo/readingrecord/ReadingRecord.java
  ReadingLogBackend/src/main/java/com/example/demo/readingrecord/ReadingRecordController.java
  ReadingLogBackend/src/main/java/com/example/demo/readingrecord/ReadingRecordRepository.java
  ReadingLogBackend/src/main/java/com/example/demo/readingrecord/ReadingRecordService.java
Labels: ✨ Feature

#142 요청 API 코드 수정 및 등등
  ReadingLogFrontend/src/api/bookStatusChange.ts
  ReadingLogFrontend/src/api/readingListAddAPI.ts
  ReadingLogFrontend/src/api/todayReadingTimeApi.ts
  ReadingLogFrontend/src/components/common/BookImgList.tsx
  ReadingLogFrontend/src/components/common/TodayReadingTime.tsx
  ReadingLogFrontend/src/components/homeLeft/MyFavoriteList.tsx
  ReadingLogFrontend/src/components/homeLeft/TimeLine.tsx
  ReadingLogFrontend/src/components/homeRight/statsItems/StatsYear.tsx
  ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/BoxThisMonthReadingList.tsx
  ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/ItemReadStatus.tsx
  ReadingLogFrontend/src/components/homeTop/BookSearchResult.tsx
  ReadingLogFrontend/src/components/modal/ModalBookPlan.tsx
  ReadingLogFrontend/src/components/modal/ModalCalendar.tsx
  ReadingLogFrontend/src/components/modal/ModalNotice.tsx
  ReadingLogFrontend/src/components/modal/ModalTrackingPlan.tsx
  ReadingLogFrontend/src/main.tsx
  ReadingLogFrontend/src/mocks/handlers/readingListHandlers.ts
  ReadingLogFrontend/src/types/aladinApi.ts
  ReadingLogFrontend/src/types/bookStatusChange.ts
  ReadingLogFrontend/src/types/commonBookListType.ts
  ReadingLogFrontend/src/types/modal.ts
  ReadingLogFrontend/src/types/readStatus.ts
  ReadingLogFrontend/src/types/readingListAdd.ts
  ReadingLogFrontend/tailwind.config.js
Labels: ✨ Feature

#147 독서 중 & 완독 토글 변경 시 리렌더링 및 기타 수정
  ReadingLogFrontend/api/proxy.js
  ReadingLogFrontend/src/components/common/BookImgList.tsx
  ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/BoxThisMonthReadingList.tsx
  ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/ItemReadStatus.tsx
  ReadingLogFrontend/src/components/homeTop/BookSearchResult.tsx
  ReadingLogFrontend/src/components/modal/ModalBookPlan.tsx
  ReadingLogFrontend/src/types/readStatus.ts
Labels: ✨ Feature

#152 네이밍 수정 및 css 수정
  ReadingLogFrontend/src/api/ThisMonthReadingListApi.ts
  ReadingLogFrontend/src/components/common/CustomScrollbar.tsx
  ReadingLogFrontend/src/components/common/MonthBookImgList.tsx
  ReadingLogFrontend/src/components/homeLeft/TimeLine.tsx
  ReadingLogFrontend/src/components/homeRight/statsItems/StatsMonth.tsx
  ReadingLogFrontend/src/components/homeRight/statsItems/StatsYear.tsx
  ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/BoxThisMonthReadingList.tsx
  ReadingLogFrontend/src/types/monthReadingList.ts
  ReadingLogFrontend/src/types/statsYear.ts
Labels: ✨ Feature

#158 타이머 독서 시간 기록
  ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/ItemStopWatch.tsx
  ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/ItemTimer.tsx
  ReadingLogFrontend/src/components/modal/ModalTrackingPlan.tsx
  ReadingLogFrontend/src/mocks/handlers/readingRecordHandlers.ts
Labels: ✨ Feature

#160 타임라인 월 표시 응답 네이밍 수정
  ReadingLogFrontend/src/components/homeLeft/TimeLine.tsx
  ReadingLogFrontend/src/mocks/dummyData/favoriteListData/favoriteListData.json
  ReadingLogFrontend/src/mocks/dummyData/favoriteListData/favoriteListData2.json
  ReadingLogFrontend/src/mocks/dummyData/thisMonthReadingListData/thisMonthReadingList.json
  ReadingLogFrontend/src/mocks/dummyData/thisMonthReadingListData/thisMonthReadingList2.json
  ReadingLogFrontend/src/mocks/dummyData/timeLineReadingListData/ReadingList-2024.json
  ReadingLogFrontend/src/mocks/dummyData/timeLineReadingListData/ReadingList-2025.json
  ReadingLogFrontend/src/types/timeLine.ts
Labels: 🧹 Clean Up

#162 삭제버튼 추가 독서계획모달 창 상황별 표시 차이, 독서 상태 변경 요청시 관련 리스트 리렌더링
  .github/workflows/deploy.yml
  ReadingLogFrontend/src/api/bookStatusChangeApi.ts
  ReadingLogFrontend/src/api/deleteBookApi.ts
  ReadingLogFrontend/src/components/common/BookImgList.tsx
  ReadingLogFrontend/src/components/common/MonthBookImgList.tsx
  ReadingLogFrontend/src/components/homeLeft/MyFavoriteList.tsx
  ReadingLogFrontend/src/components/homeRight/statsItems/StatsMonth.tsx
  ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/BoxThisMonthReadingList.tsx
  ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/ItemReadStatus.tsx
  ReadingLogFrontend/src/components/homeTop/BookSearchResult.tsx
  ReadingLogFrontend/src/components/modal/ModalBookPlan.tsx
  ReadingLogFrontend/src/components/modal/ModalNotice.tsx
  ReadingLogFrontend/src/components/modal/ModalTrackingPlan.tsx
  ReadingLogFrontend/src/main.tsx
  ReadingLogFrontend/src/store/useGlobalChangeStore.ts
  ReadingLogFrontend/src/types/bookStatusChange.ts
  ReadingLogFrontend/src/types/commonBookListType.ts
  ReadingLogFrontend/src/types/deleteBook.ts
  ReadingLogFrontend/src/types/modal.ts
  ReadingLogFrontend/src/types/readStatus.ts
  ReadingLogFrontend/src/types/statsMonth.ts
  ReadingLogFrontend/tailwind.config.js
Labels: ✨ Feature

#163 독서 상태 변경시 리렌더링 및 타임라인 표시 수정
  ReadingLogFrontend/src/components/common/BookImgList.tsx
  ReadingLogFrontend/src/components/common/MonthBookImgList.tsx
  ReadingLogFrontend/src/components/homeLeft/MyFavoriteList.tsx
  ReadingLogFrontend/src/components/homeLeft/TimeLine.tsx
  ReadingLogFrontend/src/components/homeRight/statsItems/StatsMonth.tsx
  ReadingLogFrontend/src/components/homeRight/statsItems/StatsYear.tsx
  ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/BoxThisMonthReadingList.tsx
  ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/ItemReadStatus.tsx
  ReadingLogFrontend/src/components/homeTop/BookSearchResult.tsx
  ReadingLogFrontend/src/components/homeTop/MainBookSearch.tsx
  ReadingLogFrontend/src/components/layout/LeftPage.tsx
  ReadingLogFrontend/tailwind.config.js
Labels: ✨ Feature

#164 css 수정
  ReadingLogFrontend/src/components/homeLeft/TimeLine.tsx
  ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/ItemReadStatus.tsx
  ReadingLogFrontend/src/components/modal/ModalTrackingPlan.tsx
Labels: 🧹 Clean Up

#166 회원 탈퇴시 모달 오류 수정
  ReadingLogFrontend/src/components/modal/ModalMyPage.tsx
  ReadingLogFrontend/src/mocks/handlers/userHandlers.ts
Labels: 🔧 Fix

#169 독서 상태 변경 관련 수정 사항
  ReadingLogFrontend/src/components/common/BookImgList.tsx
  ReadingLogFrontend/src/components/common/MonthBookImgList.tsx
  ReadingLogFrontend/src/components/homeLeft/TimeLine.tsx
  ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/BoxStopWatch.tsx
  ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/BoxThisMonthReadingList.tsx
  ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/BoxTimer.tsx
  ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/ItemReadStatus.tsx
  ReadingLogFrontend/src/components/homeTop/BookSearchResult.tsx
  ReadingLogFrontend/src/components/homeTop/MainBookSearch.tsx
  ReadingLogFrontend/src/components/modal/ModalBookPlan.tsx
  ReadingLogFrontend/src/components/modal/ModalTrackingPlan.tsx
  ReadingLogFrontend/src/types/monthReadingList.ts
  ReadingLogFrontend/src/types/readingListAdd.ts
  ReadingLogFrontend/tailwind.config.js
Labels: ✨ Feature

#173 독서 중 일때 제어 관련 수정
  ReadingLogFrontend/src/components/common/BookImgList.tsx
  ReadingLogFrontend/src/components/common/WarningScreen.tsx
  ReadingLogFrontend/src/components/common/YearSlideBar.tsx
  ReadingLogFrontend/src/components/homeLeft/TimeLine.tsx
  ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/BoxStopWatch.tsx
  ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/BoxThisMonthReadingList.tsx
  ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/BoxTimer.tsx
  ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/ItemReadStatus.tsx
  ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/ItemStopWatch.tsx
  ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/ItemTimer.tsx
  ReadingLogFrontend/src/components/modal/ModalBookPlan.tsx
  ReadingLogFrontend/src/components/modal/ModalCalendar.tsx
  ReadingLogFrontend/src/components/modal/ModalNotice.tsx
  ReadingLogFrontend/src/components/modal/ModalTrackingPlan.tsx
  ReadingLogFrontend/src/store/useReadingInfoStore.ts
Labels: ✨ Feature

#178 독서 타임 트래킹 중인 도서 이번 달 독서 리스트에 표시 되도록 수정, 월별 통계 그래프에 도서 호버시 책 정보 표시
  ReadingLogFrontend/src/App.tsx
  ReadingLogFrontend/src/components/common/TooltipInfo.tsx
  ReadingLogFrontend/src/components/homeRight/statsItems/StatsMonth.tsx
  ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/BoxThisMonthReadingList.tsx
  ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/ItemReadStatus.tsx
  ReadingLogFrontend/src/components/modal/ModalBookPlan.tsx
  ReadingLogFrontend/src/mocks/dummyData/statsMonthListData/statsMonthList.json
  ReadingLogFrontend/src/mocks/dummyData/statsYearListData/statsYearList.json
  ReadingLogFrontend/src/store/useReadingInfoStore.ts
  ReadingLogFrontend/src/store/useTooltipStore.ts
  ReadingLogFrontend/src/types/statsMonth.ts
  ReadingLogFrontend/tailwind.config.js
Labels: ✨ Feature

#192 코드 정리
  .github/workflows/deploy.yml
  ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/ItemStopWatch.tsx
  ReadingLogFrontend/src/components/modal/ModalMyPage.tsx
  ReadingLogFrontend/src/view/social/OAuthCallbackHandler.tsx
Labels: 🧹 Clean Up

#193 알림 모달 간격 수정 및 멘트 수정
  ReadingLogFrontend/src/components/modal/ModalMyPage.tsx
  ReadingLogFrontend/src/components/modal/ModalNotice.tsx
Labels: 🔨 Refactor

#194 UI 수정 및 api 요청 정리
  ReadingLogFrontend/src/components/homeLeft/MyFavoriteList.tsx
  ReadingLogFrontend/src/components/homeLeft/TimeLine.tsx
  ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/BoxThisMonthReadingList.tsx
  ReadingLogFrontend/src/components/homeRight/timeTrackingContainer/ItemReadStatus.tsx
  ReadingLogFrontend/src/components/modal/ModalBookPlan.tsx
  ReadingLogFrontend/src/components/modal/ModalTrackingPlan.tsx
  ReadingLogFrontend/src/main.tsx
  ReadingLogFrontend/src/mocks/handlers/readingListHandlers.ts
  ReadingLogFrontend/src/mocks/handlers/readingRecordHandlers.ts
  ReadingLogFrontend/src/store/useGlobalChangeStore.ts
Labels: ✨ Feature, 🧹 Clean Up

#197 알림 모달에 안들어간 모션효과 추가
  ReadingLogFrontend/src/components/common/BookImgList.tsx
  ReadingLogFrontend/src/components/common/TooltipInfo.tsx
  ReadingLogFrontend/src/components/homeTop/Account.tsx
  ReadingLogFrontend/src/components/homeTop/BookSearchResult.tsx
  ReadingLogFrontend/src/components/modal/ModalBookPlan.tsx
  ReadingLogFrontend/src/components/modal/ModalMyPage.tsx
  ReadingLogFrontend/src/mocks/dummyData/statsMonthListData/statsMonthList.json
Labels: ✨ Feature
